name: Build and Release KS SSH

on:
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Get Version from package.json
      id: get_version
      run: |
        VERSION=$(node -p "require('./package.json').version")
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 'stable'

    - name: Install and Build
      run: |
        bash build.sh

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "ks-ssh-go-linux-amd64,ks-ssh-go-linux-arm64,ks-ssh-go-linux-386,ks-ssh-go-linux-arm,ks-ssh-go-android-arm64,ks-ssh-go-darwin-amd64,ks-ssh-go-darwin-arm64,ks-ssh-go-windows-amd64.exe,ks-ssh-go-windows-arm64.exe"
        tag: "v${{ env.VERSION }}"
        name: "Release v${{ env.VERSION }}"
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        draft: false
        prerelease: false
