name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Tidy and Build
      run: |
        go mod tidy
        go build -o ks-ssh main.go

    - name: Test
      run: |
        ./ks-ssh
