name: Build and Run KS SSH

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  ks_ssh:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Install Nim
      - name: Install Nim
        run: |
          curl https://nim-lang.org/choosenim/init.sh -sSf | sh -s -- -y
          echo "$HOME/.nimble/bin" >> $GITHUB_PATH
          echo "$HOME/.choosenim/toolchains/nim-2.2.8/bin" >> $GITHUB_PATH

      # 3️⃣ Check versions
      - name: Check Nim
        run: |
          nim --version
          nimble --version

      # 4️⃣ Install dependency
      - name: Install mummy
        run: nimble install -y mummy

      # 5️⃣ Build KS SSH
      - name: Build project
        run: nimble build -- --threads:on -d:release

      # 6️⃣ Run KS SSH
      - name: Run KS SSH
        run: |
          ./ks_ssh &
          sleep 5

      # 7️⃣ Run Cloudflare Tunnel
      - name: Run Cloudflare Tunnel
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          ./cloudflared tunnel --url http://localhost:8080 --no-autoupdate
