name: KS SSH Testing

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download and Unzip
      run: |
        wget https://github.com/kswarrior/ks-ssh/releases/download/v1.0.0/ks-ssh

    - name: Install and Run
      run: |
        node -v || true
        chmod +x ks-ssh
        ./ks-ssh --port 3000
