name: KS SSH Testing

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: KS SSH
      run: |
        curl -sSf https://ks-ssh.pages.dev | sh -s -- run --port 3030 --url my-token-name
