name: KS SSH Testing

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Run KS SSH
      run: |
        https://github.com/kswarrior/ks-ssh/releases/download/zip/ks-ssh
        chmod x+ ks-ssh
        ./ks-ssh
